In [6]:
from tensorflow.keras.preprocessing.text import one_hot

In [7]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [8]:
##Define vocabulary size
voc_size= 10000

In [9]:
one_hot_repr = [one_hot(words,voc_size)for words in sent] 
    

In [15]:
one_hot_repr

[[3005, 7743, 7401, 5317],
 [3005, 7743, 7401, 7026],
 [3005, 7789, 7401, 7197],
 [2150, 4113, 4656, 1580, 5227],
 [2150, 4113, 4656, 1580, 9986],
 [8919, 3005, 5262, 7401, 2389],
 [1136, 644, 2480, 1580]]

In [21]:
#Word Embedding Representation
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np

In [22]:
sent_length = 8 
embedded_docs = pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 3005 7743 7401 5317]
 [   0    0    0    0 3005 7743 7401 7026]
 [   0    0    0    0 3005 7789 7401 7197]
 [   0    0    0 2150 4113 4656 1580 5227]
 [   0    0    0 2150 4113 4656 1580 9986]
 [   0    0    0 8919 3005 5262 7401 2389]
 [   0    0    0    0 1136  644 2480 1580]]


In [23]:
##Feature Representation
dim = 10

In [31]:
model = Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile(optimizer='adam',loss='mse')

c:\Users\Abhishek\PROJECTS\RNN_Simple_Project\.venv\Lib\site-packages\keras\src\layers\core\embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [32]:
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_2 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [34]:
y = model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step


In [35]:
y.shape

(7, 8, 10)

In [38]:
y[0]

array([[-0.04861827, -0.03259686,  0.00957944,  0.00569078,  0.03725718,
        -0.03090258,  0.04209212, -0.00858047, -0.01713853,  0.00986386],
       [-0.04861827, -0.03259686,  0.00957944,  0.00569078,  0.03725718,
        -0.03090258,  0.04209212, -0.00858047, -0.01713853,  0.00986386],
       [-0.04861827, -0.03259686,  0.00957944,  0.00569078,  0.03725718,
        -0.03090258,  0.04209212, -0.00858047, -0.01713853,  0.00986386],
       [-0.04861827, -0.03259686,  0.00957944,  0.00569078,  0.03725718,
        -0.03090258,  0.04209212, -0.00858047, -0.01713853,  0.00986386],
       [ 0.02963561,  0.04741495,  0.02915521, -0.0209825 ,  0.03075622,
         0.0339011 ,  0.0016734 , -0.04873681, -0.04449564,  0.02202896],
       [ 0.00156199, -0.00668889,  0.00119672, -0.04980115,  0.04481825,
        -0.00240982,  0.00479048,  0.00872002, -0.02479264,  0.03560573],
       [ 0.04059216, -0.04347853, -0.03233478,  0.0233699 , -0.0207131 ,
         0.04412383,  0.01959598,  0.03777213